### ISSUE TITLE
The most current devel branch doesn't publish messages on Raspberry Pi's

### ISSUE THREAD

**Issue by jack-digilabs** [RoverRobotics/rr_openrover_basic#12]
The current devel branch works as expected on TX2's but does not publish messages on Raspberry Pi's. I was also having the Raspberry Pi loose Wifi when I tried to catkin_make with the newest devel branch of rr_openrover_basic and would only reconnect after power cycling the Rpi.

**Comment by jack-digilabs** [comment]
I was able to get catkin_make to build on the Rpi however it still wasn't publishing any messages. 

Additionally, after switching the output in the teleop.launch file to log, the rr_openrover_basic log stdout log file is always empty and there is only one. Normally you see 2 log files per node so this might be related. 

Lastly, killing the teleop.launch on Euler (TX2) closes all the nodes normally, however on the RPi it hangs on the openrover node until it SIGTERMs to close.

**Comment by shoemakerlevy9** [comment]
Just reproduced the bug on a local master branch by adding the ros::spinOnce(); from commit 361a041. This spinOnce fixed the message bunching issue from Issue #9. Will have to investigate more.

**Comment by shoemakerlevy9** [comment]
Data rate was too much for RPi to handle. Actually listening to the comment fixed the issue

` fast_rate_(60.0), //Hz -> drop to 10Hz on Rpi`
