### ISSUE TITLE
Node name error

### ISSUE THREAD

**Issue by shoemakerlevy9** [RoverRobotics/rr_openrover_basic#3]
When I name this node "openrover_basic_node" in my launch file everything works fine, but if I switch to any other name (I tested several) I get a bunch of errors

[ERROR] [1535135946.136577115]: Failed to update param 30. getParameterData() failed. Failed to send command: fd,7d,7d,7d,0a,1e,5f
[ERROR] [1535135946.136750968]: Failed to update param 28. getParameterData() failed. Failed to send command: fd,7d,7d,7d,0a,1c,61
[ERROR] [1535135946.136889247]: Failed to update param 46. getParameterData() failed. Failed to send command: fd,7d,7d,7d,0a,2e,4f
[ERROR] [1535135946.137061694]: Failed to update param 44. getParameterData() failed. Failed to send command: fd,7d,7d,7d,0a,2c,51
[ERROR] [1535135946.137250077]: Failed to update param 42. getParameterData() failed. Failed to send command: fd,7d,7d,7d,0a,2a,53
[ERROR] [1535135946.137377472]: Failed to update param 38. getParameterData() failed. Failed to send command: fd,7d,7d,7d,0a,26,57
[ERROR] [1535135946.137551793]: Failed to update param 12. getParameterData() failed. Failed to send command: fd,7d,7d,7d,0a,0c,71
[ERROR] [1535135946.137697885]: Failed to update param 10. getParameterData() failed. Failed to send command: fd,7d,7d,7d,0a,0a,73

**Comment by jack-digilabs** [comment]
Commit 5936e4e3569d7e15eab802c77b792ca46e63032f fixed this bug
