### ISSUE TITLE
Messages are bunching

### ISSUE THREAD

**Issue by shoemakerlevy9** [RoverRobotics/rr_openrover_basic#9]
The design intent of the driver is to request the most outdated data from the highest priority list. Instead the driver is asking for all the data from a list. When it asks for slow data it takes 400ms to check all that data back on an RPi, which is longer than the fan timeout in the firmware. So having the driver this way doesn't allow you to control the fan without hitting the timeout. 

![image](https://user-images.githubusercontent.com/6597441/49836664-1de8f580-fd69-11e8-9478-e4e2e7039fa8.png)

**Comment by jack-digilabs** [comment]
Ah I removed `ros::spinOnce();` from the loop causing it to never check the timers if new data should be loaded. Adding it to anywhere in the serialManager while loop should fix it.

**Comment by shoemakerlevy9** [comment]
Fixed as of version 0.5.1
